# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export confirm_CJMLE_poisson_cpp
confirm_CJMLE_poisson_cpp <- function(response, nonmis_ind, theta0, A0, Q, C, tol = 1e-4) {
    .Call('_tcv_confirm_CJMLE_poisson_cpp', PACKAGE = 'tcv', response, nonmis_ind, theta0, A0, Q, C, tol)
}

